import pygame
from pygame.locals import *
square1 = pygame.image.load('square1.png')
platform1 = pygame.image.load('platform1.png')
blank = pygame.image.load('dark_graphic/blank.png')

city_city = pygame.image.load('backgroundz/citycity.png')
city_back = pygame.image.load('backgroundz/cityback.jpeg')

swamp_oil = pygame.image.load('backgroundz/swamp_oil.png')
cave11 = pygame.image.load('backgroundz/cave11.png')
battle_gate1 = pygame.image.load('backgroundz/battlegate1.png')

dead_oil1 = pygame.image.load('backgroundz/dead_oil1.jpeg')
dead_oil2 = pygame.image.load('backgroundz/dead_oil2.jpeg')
dead_oil3 = pygame.image.load('backgroundz/dead_oil3.jpeg')

highland1 = pygame.image.load('backgroundz/highland1.jpeg')
highland2 = pygame.image.load('backgroundz/highland2.jpeg')

blue_cave = pygame.image.load('backgroundz/blue_cave.png')
red_cave = pygame.image.load('backgroundz/red_cave.png')
red_cave_inside = pygame.image.load('backgroundz/red_cave_inside.png')

'''
girl
'''

g_turn_l1 = pygame.image.load('dark_people/girl_turn_l0000.png')
g_turn_l2 = pygame.image.load('dark_people/girl_turn_l0001.png')
g_turn_l3 = pygame.image.load('dark_people/girl_turn_l0002.png')
g_turn_l4 = pygame.image.load('dark_people/girl_turn_l0003.png')

g_turn_r1 = pygame.image.load('dark_people/girl_turn_r0000.png')
g_turn_r2 = pygame.image.load('dark_people/girl_turn_r0001.png')
g_turn_r3 = pygame.image.load('dark_people/girl_turn_r0002.png')
g_turn_r4 = pygame.image.load('dark_people/girl_turn_r0003.png')

g_walk_l1 = pygame.image.load('dark_people/girl_walk_l0000.png')
g_walk_l2 = pygame.image.load('dark_people/girl_walk_l0001.png')
g_walk_l3 = pygame.image.load('dark_people/girl_walk_l0002.png')
g_walk_l4 = pygame.image.load('dark_people/girl_walk_l0003.png')
g_walk_l5 = pygame.image.load('dark_people/girl_walk_l0004.png')

g_walk_r1 = pygame.image.load('dark_people/girl_walk_r0000.png')
g_walk_r2 = pygame.image.load('dark_people/girl_walk_r0001.png')
g_walk_r3 = pygame.image.load('dark_people/girl_walk_r0002.png')
g_walk_r4 = pygame.image.load('dark_people/girl_walk_r0003.png')
g_walk_r5 = pygame.image.load('dark_people/girl_walk_r0004.png')

'''
Hinin
'''
p3_stand1 = pygame.image.load('dark_people/hinin0000.png')
p3_stand2 = pygame.image.load('dark_people/hinin0001.png')
p3_stand3 = pygame.image.load('dark_people/hinin0002.png')
p3_stand4 = pygame.image.load('dark_people/hinin0003.png')
p3_stand5 = pygame.image.load('dark_people/hinin0004.png')
p3_stand6 = pygame.image.load('dark_people/hinin0005.png')
p3_stand7 = pygame.image.load('dark_people/hinin0006.png')


'''
People1
'''

p1_stand_l = pygame.image.load('dark_people/p1_confront_l0000.png')
p1_stand_r = pygame.image.load('dark_people/p1_confront_r0000.png')

p1_turning1 = pygame.image.load('dark_people/p1_turning0000.png')
p1_turning2 = pygame.image.load('dark_people/p1_turning0001.png')
p1_turning3 = pygame.image.load('dark_people/p1_turning0002.png')
p1_turning4 = pygame.image.load('dark_people/p1_turning0003.png')
p1_turning5 = pygame.image.load('dark_people/p1_turning0004.png')

p1_con_l1 = pygame.image.load('dark_people/p1_confront_l0000.png')
p1_con_l2 = pygame.image.load('dark_people/p1_confront_l0001.png')
p1_con_l3 = pygame.image.load('dark_people/p1_confront_l0002.png')
p1_con_l4 = pygame.image.load('dark_people/p1_confront_l0003.png')
p1_con_l5 = pygame.image.load('dark_people/p1_confront_l0004.png')
p1_con_l6 = pygame.image.load('dark_people/p1_confront_l0005.png')
p1_con_l7 = pygame.image.load('dark_people/p1_confront_l0006.png')
p1_con_l8 = pygame.image.load('dark_people/p1_confront_l0007.png')
p1_con_l9 = pygame.image.load('dark_people/p1_confront_l0008.png')

p1_con_r1 = pygame.image.load('dark_people/p1_confront_r0000.png')
p1_con_r2 = pygame.image.load('dark_people/p1_confront_r0001.png')
p1_con_r3 = pygame.image.load('dark_people/p1_confront_r0002.png')
p1_con_r4 = pygame.image.load('dark_people/p1_confront_r0003.png')
p1_con_r5 = pygame.image.load('dark_people/p1_confront_r0004.png')
p1_con_r6 = pygame.image.load('dark_people/p1_confront_r0005.png')
p1_con_r7 = pygame.image.load('dark_people/p1_confront_r0006.png')
p1_con_r8 = pygame.image.load('dark_people/p1_confront_r0007.png')
p1_con_r9 = pygame.image.load('dark_people/p1_confront_r0008.png')
p1_con_r10 = pygame.image.load('dark_people/p1_confront_r0009.png')
p1_con_r11 = pygame.image.load('dark_people/p1_confront_r0010.png')
p1_con_r12 = pygame.image.load('dark_people/p1_confront_r0011.png')


'''
People2
'''

p2_turning1 = pygame.image.load('dark_people/p2_turning0000.png')
p2_turning2 = pygame.image.load('dark_people/p2_turning0001.png')
p2_turning3 = pygame.image.load('dark_people/p2_turning0002.png')
p2_turning4 = pygame.image.load('dark_people/p2_turning0003.png')
p2_turning5 = pygame.image.load('dark_people/p2_turning0004.png')

p2_con_l1 = pygame.image.load('dark_people/p2_confront_l0000.png')
p2_con_l2 = pygame.image.load('dark_people/p2_confront_l0001.png')
p2_con_l3 = pygame.image.load('dark_people/p2_confront_l0002.png')
p2_con_l4 = pygame.image.load('dark_people/p2_confront_l0003.png')
p2_con_l5 = pygame.image.load('dark_people/p2_confront_l0004.png')
p2_con_l6 = pygame.image.load('dark_people/p2_confront_l0005.png')
p2_con_l7 = pygame.image.load('dark_people/p2_confront_l0006.png')
p2_con_l8 = pygame.image.load('dark_people/p2_confront_l0007.png')

p2_con_r1 = pygame.image.load('dark_people/p2_confront_r0000.png')
p2_con_r2 = pygame.image.load('dark_people/p2_confront_r0001.png')
p2_con_r3 = pygame.image.load('dark_people/p2_confront_r0002.png')
p2_con_r4 = pygame.image.load('dark_people/p2_confront_r0003.png')
p2_con_r5 = pygame.image.load('dark_people/p2_confront_r0004.png')
p2_con_r6 = pygame.image.load('dark_people/p2_confront_r0005.png')


'''
S H I E L D L I K
'''
s_idle_1 = pygame.image.load('dark_shieldlik/idle0000.png')
s_idle_2 = pygame.image.load('dark_shieldlik/idle0001.png')
s_idle_3 = pygame.image.load('dark_shieldlik/idle0002.png')
s_idle_4 = pygame.image.load('dark_shieldlik/idle0003.png')
s_idle_5 = pygame.image.load('dark_shieldlik/idle0004.png')
s_idle_6 = pygame.image.load('dark_shieldlik/idle0005.png')
s_idle_7 = pygame.image.load('dark_shieldlik/idle0006.png')

sh_stand_l1 = pygame.image.load('dark_shieldlik/standing_l0000.png')
sh_stand_l2 = pygame.image.load('dark_shieldlik/standing_l0001.png')
sh_stand_l3 = pygame.image.load('dark_shieldlik/standing_l0002.png')
sh_stand_l4 = pygame.image.load('dark_shieldlik/standing_l0003.png')
sh_stand_l5 = pygame.image.load('dark_shieldlik/standing_l0004.png')
sh_stand_l6 = pygame.image.load('dark_shieldlik/standing_l0005.png')

sh_stand_r1 = pygame.image.load('dark_shieldlik/standing_r0000.png')
sh_stand_r2 = pygame.image.load('dark_shieldlik/standing_r0001.png')
sh_stand_r3 = pygame.image.load('dark_shieldlik/standing_r0002.png')
sh_stand_r4 = pygame.image.load('dark_shieldlik/standing_r0003.png')
sh_stand_r5 = pygame.image.load('dark_shieldlik/standing_r0004.png')
sh_stand_r6 = pygame.image.load('dark_shieldlik/standing_r0005.png')

s_turning_lr1 = pygame.image.load('dark_shieldlik/turning_l_r0000.png')
s_turning_lr2 = pygame.image.load('dark_shieldlik/turning_l_r0001.png')
s_turning_lr3 = pygame.image.load('dark_shieldlik/turning_l_r0002.png')
s_turning_lr4 = pygame.image.load('dark_shieldlik/turning_l_r0003.png')
s_turning_lr5 = pygame.image.load('dark_shieldlik/turning_l_r0004.png')
s_turning_lr6 = pygame.image.load('dark_shieldlik/turning_l_r0005.png')

s_walking_l1 = pygame.image.load('dark_shieldlik/walking_l0000.png')
s_walking_l2 = pygame.image.load('dark_shieldlik/walking_l0001.png')
s_walking_l3 = pygame.image.load('dark_shieldlik/walking_l0002.png')
s_walking_l4 = pygame.image.load('dark_shieldlik/walking_l0003.png')
s_walking_l5 = pygame.image.load('dark_shieldlik/walking_l0004.png')
s_walking_l6 = pygame.image.load('dark_shieldlik/walking_l0005.png')
s_walking_l7 = pygame.image.load('dark_shieldlik/walking_l0006.png')
s_walking_l8 = pygame.image.load('dark_shieldlik/walking_l0007.png')

s_walking_back_l1 = pygame.image.load('dark_shieldlik/walkback_l0000.png')
s_walking_back_l2 = pygame.image.load('dark_shieldlik/walkback_l0001.png')
s_walking_back_l3 = pygame.image.load('dark_shieldlik/walkback_l0002.png')
s_walking_back_l4 = pygame.image.load('dark_shieldlik/walkback_l0003.png')
s_walking_back_l5 = pygame.image.load('dark_shieldlik/walkback_l0004.png')

s_walking_r1 = pygame.image.load('dark_shieldlik/walking_r0000.png')
s_walking_r2 = pygame.image.load('dark_shieldlik/walking_r0001.png')
s_walking_r3 = pygame.image.load('dark_shieldlik/walking_r0002.png')
s_walking_r4 = pygame.image.load('dark_shieldlik/walking_r0003.png')
s_walking_r5 = pygame.image.load('dark_shieldlik/walking_r0004.png')
s_walking_r6 = pygame.image.load('dark_shieldlik/walking_r0005.png')
s_walking_r7 = pygame.image.load('dark_shieldlik/walking_r0006.png')
s_walking_r8 = pygame.image.load('dark_shieldlik/walking_r0007.png')

s_walking_back_r1 = pygame.image.load('dark_shieldlik/walkback_r0000.png')
s_walking_back_r2 = pygame.image.load('dark_shieldlik/walkback_r0001.png')
s_walking_back_r3 = pygame.image.load('dark_shieldlik/walkback_r0002.png')
s_walking_back_r4 = pygame.image.load('dark_shieldlik/walkback_r0003.png')
s_walking_back_r5 = pygame.image.load('dark_shieldlik/walkback_r0004.png')

s_strike1_l1 = pygame.image.load('dark_shieldlik/strike1_l0000.png')
s_strike1_l2 = pygame.image.load('dark_shieldlik/strike1_l0001.png')
s_strike1_l3 = pygame.image.load('dark_shieldlik/strike1_l0002.png')
s_strike1_l4 = pygame.image.load('dark_shieldlik/strike1_l0003.png')
s_strike1_l5 = pygame.image.load('dark_shieldlik/strike1_l0004.png')

s_strike2_l1 = pygame.image.load('dark_shieldlik/strike2_l0000.png')
s_strike2_l2 = pygame.image.load('dark_shieldlik/strike2_l0001.png')
s_strike2_l3 = pygame.image.load('dark_shieldlik/strike2_l0002.png')
s_strike2_l4 = pygame.image.load('dark_shieldlik/strike2_l0003.png')
s_strike2_l5 = pygame.image.load('dark_shieldlik/strike2_l0004.png')
s_strike2_l6 = pygame.image.load('dark_shieldlik/strike2_l0005.png')
s_strike2_l7 = pygame.image.load('dark_shieldlik/strike2_l0006.png')
s_strike2_l8 = pygame.image.load('dark_shieldlik/strike2_l0007.png')
s_strike2_l9 = pygame.image.load('dark_shieldlik/strike2_l0008.png')
s_strike2_l10 = pygame.image.load('dark_shieldlik/strike2_l0009.png')
s_strike2_l11 = pygame.image.load('dark_shieldlik/strike2_l0010.png')
s_strike2_l12 = pygame.image.load('dark_shieldlik/strike2_l0011.png')
s_strike2_l13 = pygame.image.load('dark_shieldlik/strike2_l0012.png')
s_strike2_l14 = pygame.image.load('dark_shieldlik/strike2_l0013.png')
s_strike2_l15 = pygame.image.load('dark_shieldlik/strike2_l0014.png')
s_strike2_l16 = pygame.image.load('dark_shieldlik/strike2_l0015.png')

s_strike3_l1 = pygame.image.load('dark_shieldlik/strike3_l0000.png')
s_strike3_l2 = pygame.image.load('dark_shieldlik/strike3_l0001.png')
s_strike3_l3 = pygame.image.load('dark_shieldlik/strike3_l0002.png')
s_strike3_l4 = pygame.image.load('dark_shieldlik/strike3_l0003.png')
s_strike3_l5 = pygame.image.load('dark_shieldlik/strike3_l0004.png')
s_strike3_l6 = pygame.image.load('dark_shieldlik/strike3_l0005.png')
s_strike3_l7 = pygame.image.load('dark_shieldlik/strike3_l0006.png')

s_strike1_r1 = pygame.image.load('dark_shieldlik/strike1_r0000.png')
s_strike1_r2 = pygame.image.load('dark_shieldlik/strike1_r0001.png')
s_strike1_r3 = pygame.image.load('dark_shieldlik/strike1_r0002.png')
s_strike1_r4 = pygame.image.load('dark_shieldlik/strike1_r0003.png')
s_strike1_r5 = pygame.image.load('dark_shieldlik/strike1_r0004.png')
s_strike1_r6 = pygame.image.load('dark_shieldlik/strike1_r0005.png')
s_strike1_r7 = pygame.image.load('dark_shieldlik/strike1_r0006.png')
s_strike1_r8 = pygame.image.load('dark_shieldlik/strike1_r0007.png')

s_strike2_r1 = pygame.image.load('dark_shieldlik/strike2_r0000.png')
s_strike2_r2 = pygame.image.load('dark_shieldlik/strike2_r0001.png')
s_strike2_r3 = pygame.image.load('dark_shieldlik/strike2_r0002.png')
s_strike2_r4 = pygame.image.load('dark_shieldlik/strike2_r0003.png')
s_strike2_r5 = pygame.image.load('dark_shieldlik/strike2_r0004.png')
s_strike2_r6 = pygame.image.load('dark_shieldlik/strike2_r0005.png')
s_strike2_r7 = pygame.image.load('dark_shieldlik/strike2_r0006.png')
s_strike2_r8 = pygame.image.load('dark_shieldlik/strike2_r0007.png')

s_strike3_r1 = pygame.image.load('dark_shieldlik/strike3_r0000.png')
s_strike3_r2 = pygame.image.load('dark_shieldlik/strike3_r0001.png')
s_strike3_r3 = pygame.image.load('dark_shieldlik/strike3_r0002.png')
s_strike3_r4 = pygame.image.load('dark_shieldlik/strike3_r0003.png')
s_strike3_r5 = pygame.image.load('dark_shieldlik/strike3_r0004.png')
s_strike3_r6 = pygame.image.load('dark_shieldlik/strike3_r0005.png')
s_strike3_r7 = pygame.image.load('dark_shieldlik/strike3_r0006.png')
s_strike3_r8 = pygame.image.load('dark_shieldlik/strike3_r0007.png')
s_strike3_r9 = pygame.image.load('dark_shieldlik/strike3_r0008.png')
s_strike3_r10 = pygame.image.load('dark_shieldlik/strike3_r0009.png')

s_death1_l1 = pygame.image.load('dark_shieldlik/death1_l0000.png')
s_death1_l2 = pygame.image.load('dark_shieldlik/death1_l0001.png')
s_death1_l3 = pygame.image.load('dark_shieldlik/death1_l0002.png')
s_death1_l4 = pygame.image.load('dark_shieldlik/death1_l0003.png')
s_death1_l5 = pygame.image.load('dark_shieldlik/death1_l0004.png')
s_death1_l6 = pygame.image.load('dark_shieldlik/death1_l0005.png')
s_death1_l7 = pygame.image.load('dark_shieldlik/death1_l0006.png')
s_death1_l8 = pygame.image.load('dark_shieldlik/death1_l0007.png')
s_death1_l9 = pygame.image.load('dark_shieldlik/death1_l0008.png')
s_death1_l10 = pygame.image.load('dark_shieldlik/death1_l0009.png')
s_death1_l11 = pygame.image.load('dark_shieldlik/death1_l0010.png')
s_death1_l12 = pygame.image.load('dark_shieldlik/death1_l0011.png')
s_death1_l13 = pygame.image.load('dark_shieldlik/death1_l0012.png')
s_death1_l14 = pygame.image.load('dark_shieldlik/death1_l0013.png')
s_death1_l15 = pygame.image.load('dark_shieldlik/death1_l0014.png')

s_death2_l1 = pygame.image.load('dark_shieldlik/death2_l0000.png')
s_death2_l2 = pygame.image.load('dark_shieldlik/death2_l0001.png')
s_death2_l3 = pygame.image.load('dark_shieldlik/death2_l0002.png')
s_death2_l4 = pygame.image.load('dark_shieldlik/death2_l0003.png')
s_death2_l5 = pygame.image.load('dark_shieldlik/death2_l0004.png')
s_death2_l6 = pygame.image.load('dark_shieldlik/death2_l0005.png')
s_death2_l7 = pygame.image.load('dark_shieldlik/death2_l0006.png')
s_death2_l8 = pygame.image.load('dark_shieldlik/death2_l0007.png')
s_death2_l9 = pygame.image.load('dark_shieldlik/death2_l0008.png')
s_death2_l10 = pygame.image.load('dark_shieldlik/death2_l0009.png')
s_death2_l11 = pygame.image.load('dark_shieldlik/death2_l0010.png')
s_death2_l12 = pygame.image.load('dark_shieldlik/death2_l0011.png')
s_death2_l13 = pygame.image.load('dark_shieldlik/death2_l0012.png')
s_death2_l14 = pygame.image.load('dark_shieldlik/death2_l0013.png')
s_death2_l15 = pygame.image.load('dark_shieldlik/death2_l0014.png')

s_death3_l1 = pygame.image.load('dark_shieldlik/death3_l0000.png')
s_death3_l2 = pygame.image.load('dark_shieldlik/death3_l0001.png')
s_death3_l3 = pygame.image.load('dark_shieldlik/death3_l0002.png')
s_death3_l4 = pygame.image.load('dark_shieldlik/death3_l0003.png')
s_death3_l5 = pygame.image.load('dark_shieldlik/death3_l0004.png')
s_death3_l6 = pygame.image.load('dark_shieldlik/death3_l0005.png')
s_death3_l7 = pygame.image.load('dark_shieldlik/death3_l0006.png')
s_death3_l8 = pygame.image.load('dark_shieldlik/death3_l0007.png')
s_death3_l9 = pygame.image.load('dark_shieldlik/death3_l0008.png')
s_death3_l10 = pygame.image.load('dark_shieldlik/death3_l0009.png')
s_death3_l11 = pygame.image.load('dark_shieldlik/death3_l0010.png')
s_death3_l12 = pygame.image.load('dark_shieldlik/death3_l0011.png')
s_death3_l13 = pygame.image.load('dark_shieldlik/death3_l0012.png')
s_death3_l14 = pygame.image.load('dark_shieldlik/death3_l0013.png')
s_death3_l15 = pygame.image.load('dark_shieldlik/death3_l0014.png')
s_death3_l16 = pygame.image.load('dark_shieldlik/death3_l0015.png')
s_death3_l17 = pygame.image.load('dark_shieldlik/death3_l0016.png')

s_death1_r1 = pygame.image.load('dark_shieldlik/death1_r0000.png')
s_death1_r2 = pygame.image.load('dark_shieldlik/death1_r0001.png')
s_death1_r3 = pygame.image.load('dark_shieldlik/death1_r0002.png')
s_death1_r4 = pygame.image.load('dark_shieldlik/death1_r0003.png')
s_death1_r5 = pygame.image.load('dark_shieldlik/death1_r0004.png')
s_death1_r6 = pygame.image.load('dark_shieldlik/death1_r0005.png')
s_death1_r7 = pygame.image.load('dark_shieldlik/death1_r0006.png')
s_death1_r8 = pygame.image.load('dark_shieldlik/death1_r0007.png')
s_death1_r9 = pygame.image.load('dark_shieldlik/death1_r0008.png')
s_death1_r10 = pygame.image.load('dark_shieldlik/death1_r0009.png')
s_death1_r11 = pygame.image.load('dark_shieldlik/death1_r0010.png')
s_death1_r12 = pygame.image.load('dark_shieldlik/death1_r0011.png')
s_death1_r13 = pygame.image.load('dark_shieldlik/death1_r0012.png')
s_death1_r14 = pygame.image.load('dark_shieldlik/death1_r0013.png')

s_death2_r1 = pygame.image.load('dark_shieldlik/death2_r0000.png')
s_death2_r2 = pygame.image.load('dark_shieldlik/death2_r0001.png')
s_death2_r3 = pygame.image.load('dark_shieldlik/death2_r0002.png')
s_death2_r4 = pygame.image.load('dark_shieldlik/death2_r0003.png')
s_death2_r5 = pygame.image.load('dark_shieldlik/death2_r0004.png')
s_death2_r6 = pygame.image.load('dark_shieldlik/death2_r0005.png')
s_death2_r7 = pygame.image.load('dark_shieldlik/death2_r0006.png')
s_death2_r8 = pygame.image.load('dark_shieldlik/death2_r0007.png')
s_death2_r9 = pygame.image.load('dark_shieldlik/death2_r0008.png')
s_death2_r10 = pygame.image.load('dark_shieldlik/death2_r0009.png')
s_death2_r11 = pygame.image.load('dark_shieldlik/death2_r0010.png')
s_death2_r12 = pygame.image.load('dark_shieldlik/death2_r0011.png')
s_death2_r13 = pygame.image.load('dark_shieldlik/death2_r0012.png')
s_death2_r14 = pygame.image.load('dark_shieldlik/death2_r0013.png')
s_death2_r15 = pygame.image.load('dark_shieldlik/death2_r0014.png')
s_death2_r16 = pygame.image.load('dark_shieldlik/death2_r0015.png')
s_death2_r17 = pygame.image.load('dark_shieldlik/death2_r0016.png')

'''
T R O G L I K
'''

t_stand_l1 = pygame.image.load('dark_troglik/standing_turning0000.png')
t_stand_l2 = pygame.image.load('dark_troglik/standing_turning0001.png')
t_stand_l3 = pygame.image.load('dark_troglik/standing_turning0002.png')
t_stand_l4 = pygame.image.load('dark_troglik/standing_turning0003.png')
t_stand_l5 = pygame.image.load('dark_troglik/standing_turning0004.png')

t_turning1 = pygame.image.load('dark_troglik/standing_turning0005.png')
t_turning2 = pygame.image.load('dark_troglik/standing_turning0006.png')
t_turning3 = pygame.image.load('dark_troglik/standing_turning0007.png')
t_turning4 = pygame.image.load('dark_troglik/standing_turning0008.png')

t_turning5 = pygame.image.load('dark_troglik/standing_turning0014.png')
t_turning6 = pygame.image.load('dark_troglik/standing_turning0015.png')
t_turning7 = pygame.image.load('dark_troglik/standing_turning0016.png')
t_turning8 = pygame.image.load('dark_troglik/standing_turning0017.png')

t_stand_r1 = pygame.image.load('dark_troglik/standing_turning0009.png')
t_stand_r2 = pygame.image.load('dark_troglik/standing_turning0010.png')
t_stand_r3 = pygame.image.load('dark_troglik/standing_turning0011.png')
t_stand_r4 = pygame.image.load('dark_troglik/standing_turning0012.png')
t_stand_r5 = pygame.image.load('dark_troglik/standing_turning0013.png')

t_walk_l1 = pygame.image.load('dark_troglik/walking_left0000.png')
t_walk_l2 = pygame.image.load('dark_troglik/walking_left0001.png')
t_walk_l3 = pygame.image.load('dark_troglik/walking_left0002.png')
t_walk_l4 = pygame.image.load('dark_troglik/walking_left0003.png')
t_walk_l5 = pygame.image.load('dark_troglik/walking_left0004.png')
t_walk_l6 = pygame.image.load('dark_troglik/walking_left0005.png')
t_walk_l7 = pygame.image.load('dark_troglik/walking_left0006.png')
t_walk_l8 = pygame.image.load('dark_troglik/walking_left0007.png')

t_walk_r1 = pygame.image.load('dark_troglik/walking_right0000.png')
t_walk_r2 = pygame.image.load('dark_troglik/walking_right0001.png')
t_walk_r3 = pygame.image.load('dark_troglik/walking_right0002.png')
t_walk_r4 = pygame.image.load('dark_troglik/walking_right0003.png')
t_walk_r5 = pygame.image.load('dark_troglik/walking_right0004.png')
t_walk_r6 = pygame.image.load('dark_troglik/walking_right0005.png')
t_walk_r7 = pygame.image.load('dark_troglik/walking_right0006.png')
t_walk_r8 = pygame.image.load('dark_troglik/walking_right0007.png')

t_strike1_l1 = pygame.image.load('dark_troglik/strike_left0000.png')
t_strike1_l2 = pygame.image.load('dark_troglik/strike_left0001.png')
t_strike1_l3 = pygame.image.load('dark_troglik/strike_left0002.png')
t_strike1_l4 = pygame.image.load('dark_troglik/strike_left0003.png')
t_strike1_l5 = pygame.image.load('dark_troglik/strike_left0004.png')
t_strike1_l6 = pygame.image.load('dark_troglik/strike_left0005.png')
t_strike1_l7 = pygame.image.load('dark_troglik/strike_left0006.png')
t_strike1_l8 = pygame.image.load('dark_troglik/strike_left0007.png')
t_strike1_l9 = pygame.image.load('dark_troglik/strike_left0008.png')
t_strike1_l10 = pygame.image.load('dark_troglik/strike_left0009.png')

t_strike2_l1 = pygame.image.load('dark_troglik/strike_left0010.png')
t_strike2_l2 = pygame.image.load('dark_troglik/strike_left0011.png')
t_strike2_l3 = pygame.image.load('dark_troglik/strike_left0012.png')
t_strike2_l4 = pygame.image.load('dark_troglik/strike_left0013.png')
t_strike2_l5 = pygame.image.load('dark_troglik/strike_left0014.png')
t_strike2_l6 = pygame.image.load('dark_troglik/strike_left0015.png')
t_strike2_l7 = pygame.image.load('dark_troglik/strike_left0016.png')
t_strike2_l8 = pygame.image.load('dark_troglik/strike_left0017.png')
t_strike2_l9 = pygame.image.load('dark_troglik/strike_left0018.png')
t_strike2_l10 = pygame.image.load('dark_troglik/strike_left0019.png')

t_strike3_l1 = pygame.image.load('dark_troglik/strike_left0020.png')
t_strike3_l2 = pygame.image.load('dark_troglik/strike_left0021.png')
t_strike3_l3 = pygame.image.load('dark_troglik/strike_left0022.png')
t_strike3_l4 = pygame.image.load('dark_troglik/strike_left0023.png')
t_strike3_l5 = pygame.image.load('dark_troglik/strike_left0024.png')
t_strike3_l6 = pygame.image.load('dark_troglik/strike_left0025.png')
t_strike3_l7 = pygame.image.load('dark_troglik/strike_left0026.png')
t_strike3_l8 = pygame.image.load('dark_troglik/strike_left0027.png')
t_strike3_l9 = pygame.image.load('dark_troglik/strike_left0028.png')
t_strike3_l10 = pygame.image.load('dark_troglik/strike_left0029.png')
t_strike3_l11 = pygame.image.load('dark_troglik/strike_left0030.png')

t_strike4_l1 = pygame.image.load('dark_troglik/strike_left0033.png')
t_strike4_l2 = pygame.image.load('dark_troglik/strike_left0034.png')
t_strike4_l3 = pygame.image.load('dark_troglik/strike_left0035.png')
t_strike4_l4 = pygame.image.load('dark_troglik/strike_left0036.png')
t_strike4_l5 = pygame.image.load('dark_troglik/strike_left0037.png')
t_strike4_l6 = pygame.image.load('dark_troglik/strike_left0038.png')
t_strike4_l7 = pygame.image.load('dark_troglik/strike_left0039.png')
t_strike4_l8 = pygame.image.load('dark_troglik/strike_left0040.png')
t_strike4_l9 = pygame.image.load('dark_troglik/strike_left0041.png')
t_strike4_l10 = pygame.image.load('dark_troglik/strike_left0042.png')

t_strike1_r1 = pygame.image.load('dark_troglik/strike_right0000.png')
t_strike1_r2 = pygame.image.load('dark_troglik/strike_right0001.png')
t_strike1_r3 = pygame.image.load('dark_troglik/strike_right0002.png')
t_strike1_r4 = pygame.image.load('dark_troglik/strike_right0003.png')
t_strike1_r5 = pygame.image.load('dark_troglik/strike_right0004.png')
t_strike1_r6 = pygame.image.load('dark_troglik/strike_right0005.png')
t_strike1_r7 = pygame.image.load('dark_troglik/strike_right0006.png')
t_strike1_r8 = pygame.image.load('dark_troglik/strike_right0007.png')
t_strike1_r9 = pygame.image.load('dark_troglik/strike_right0008.png')

t_strike2_r1 = pygame.image.load('dark_troglik/strike_right0017.png')
t_strike2_r2 = pygame.image.load('dark_troglik/strike_right0018.png')
t_strike2_r3 = pygame.image.load('dark_troglik/strike_right0019.png')
t_strike2_r4 = pygame.image.load('dark_troglik/strike_right0020.png')
t_strike2_r5 = pygame.image.load('dark_troglik/strike_right0021.png')
t_strike2_r6 = pygame.image.load('dark_troglik/strike_right0022.png')
t_strike2_r7 = pygame.image.load('dark_troglik/strike_right0023.png')
t_strike2_r8 = pygame.image.load('dark_troglik/strike_right0024.png')
t_strike2_r9 = pygame.image.load('dark_troglik/strike_right0025.png')
t_strike2_r10 = pygame.image.load('dark_troglik/strike_right0026.png')
t_strike2_r11 = pygame.image.load('dark_troglik/strike_right0027.png')
t_strike2_r12 = pygame.image.load('dark_troglik/strike_right0028.png')
t_strike2_r13 = pygame.image.load('dark_troglik/strike_right0029.png')

t_strike3_r1 = pygame.image.load('dark_troglik/strike_right0032.png')
t_strike3_r2 = pygame.image.load('dark_troglik/strike_right0033.png')
t_strike3_r3 = pygame.image.load('dark_troglik/strike_right0034.png')
t_strike3_r4 = pygame.image.load('dark_troglik/strike_right0035.png')
t_strike3_r5 = pygame.image.load('dark_troglik/strike_right0036.png')
t_strike3_r6 = pygame.image.load('dark_troglik/strike_right0037.png')
t_strike3_r7 = pygame.image.load('dark_troglik/strike_right0038.png')

t_jump_left1 = pygame.image.load('dark_troglik/jump_left0000.png')
t_jump_left2 = pygame.image.load('dark_troglik/jump_left0001.png')
t_jump_left3 = pygame.image.load('dark_troglik/jump_left0002.png')
t_jump_left4 = pygame.image.load('dark_troglik/jump_left0003.png')
t_jump_left5 = pygame.image.load('dark_troglik/jump_left0004.png')

t_jump_right1 = pygame.image.load('dark_troglik/jump_right0000.png')
t_jump_right2 = pygame.image.load('dark_troglik/jump_right0001.png')
t_jump_right3 = pygame.image.load('dark_troglik/jump_right0002.png')
t_jump_right4 = pygame.image.load('dark_troglik/jump_right0003.png')
t_jump_right5 = pygame.image.load('dark_troglik/jump_right0004.png')

t_death1_l1 = pygame.image.load('dark_troglik/death1_left0000.png')
t_death1_l2 = pygame.image.load('dark_troglik/death1_left0001.png')
t_death1_l3 = pygame.image.load('dark_troglik/death1_left0002.png')
t_death1_l4 = pygame.image.load('dark_troglik/death1_left0003.png')
t_death1_l5 = pygame.image.load('dark_troglik/death1_left0004.png')
t_death1_l6 = pygame.image.load('dark_troglik/death1_left0005.png')
t_death1_l7 = pygame.image.load('dark_troglik/death1_left0006.png')
t_death1_l8 = pygame.image.load('dark_troglik/death1_left0007.png')
t_death1_l9 = pygame.image.load('dark_troglik/death1_left0008.png')
t_death1_l10 = pygame.image.load('dark_troglik/death1_left0009.png')
t_death1_l11 = pygame.image.load('dark_troglik/death1_left0010.png')
t_death1_l12 = pygame.image.load('dark_troglik/death1_left0011.png')
t_death1_l13 = pygame.image.load('dark_troglik/death1_left0012.png')

t_death2_l1 = pygame.image.load('dark_troglik/death2_left0000.png')
t_death2_l2 = pygame.image.load('dark_troglik/death2_left0001.png')
t_death2_l3 = pygame.image.load('dark_troglik/death2_left0002.png')
t_death2_l4 = pygame.image.load('dark_troglik/death2_left0003.png')
t_death2_l5 = pygame.image.load('dark_troglik/death2_left0004.png')
t_death2_l6 = pygame.image.load('dark_troglik/death2_left0005.png')
t_death2_l7 = pygame.image.load('dark_troglik/death2_left0006.png')
t_death2_l8 = pygame.image.load('dark_troglik/death2_left0007.png')
t_death2_l9 = pygame.image.load('dark_troglik/death2_left0008.png')
t_death2_l10 = pygame.image.load('dark_troglik/death2_left0009.png')
t_death2_l11 = pygame.image.load('dark_troglik/death2_left0010.png')

t_death1_r1 = pygame.image.load('dark_troglik/death1_right0000.png')
t_death1_r2 = pygame.image.load('dark_troglik/death1_right0001.png')
t_death1_r3 = pygame.image.load('dark_troglik/death1_right0002.png')
t_death1_r4 = pygame.image.load('dark_troglik/death1_right0003.png')
t_death1_r5 = pygame.image.load('dark_troglik/death1_right0004.png')
t_death1_r6 = pygame.image.load('dark_troglik/death1_right0005.png')
t_death1_r7 = pygame.image.load('dark_troglik/death1_right0006.png')
t_death1_r8 = pygame.image.load('dark_troglik/death1_right0007.png')
t_death1_r9 = pygame.image.load('dark_troglik/death1_right0008.png')
t_death1_r10 = pygame.image.load('dark_troglik/death1_right0009.png')
t_death1_r11 = pygame.image.load('dark_troglik/death1_right0010.png')
t_death1_r12 = pygame.image.load('dark_troglik/death1_right0011.png')
t_death1_r13 = pygame.image.load('dark_troglik/death1_right0012.png')
t_death1_r14 = pygame.image.load('dark_troglik/death1_right0013.png')

t_death2_r1 = pygame.image.load('dark_troglik/death2_right0000.png')
t_death2_r2 = pygame.image.load('dark_troglik/death2_right0001.png')
t_death2_r3 = pygame.image.load('dark_troglik/death2_right0002.png')
t_death2_r4 = pygame.image.load('dark_troglik/death2_right0003.png')
t_death2_r5 = pygame.image.load('dark_troglik/death2_right0004.png')
t_death2_r6 = pygame.image.load('dark_troglik/death2_right0005.png')
t_death2_r7 = pygame.image.load('dark_troglik/death2_right0006.png')
t_death2_r8 = pygame.image.load('dark_troglik/death2_right0007.png')
t_death2_r9 = pygame.image.load('dark_troglik/death2_right0008.png')
t_death2_r10 = pygame.image.load('dark_troglik/death2_right0009.png')
t_death2_r11 = pygame.image.load('dark_troglik/death2_right0010.png')

'''
S P E A R L I K
'''
s_stand_l1 = pygame.image.load('dark_spearlik/standing_turning0000.png')
s_stand_l2 = pygame.image.load('dark_spearlik/standing_turning0001.png')
s_stand_l3 = pygame.image.load('dark_spearlik/standing_turning0002.png')
s_stand_l4 = pygame.image.load('dark_spearlik/standing_turning0003.png')
s_stand_l5 = pygame.image.load('dark_spearlik/standing_turning0004.png')
s_stand_l5 = pygame.image.load('dark_spearlik/standing_turning0005.png')

s_stand_r1 = pygame.image.load('dark_spearlik/standing_turning0011.png')
s_stand_r2 = pygame.image.load('dark_spearlik/standing_turning0012.png')
s_stand_r3 = pygame.image.load('dark_spearlik/standing_turning0013.png')
s_stand_r4 = pygame.image.load('dark_spearlik/standing_turning0014.png')
s_stand_r5 = pygame.image.load('dark_spearlik/standing_turning0015.png')
s_stand_r5 = pygame.image.load('dark_spearlik/standing_turning0016.png')

s_turning1 = pygame.image.load('dark_spearlik/standing_turning0006.png')
s_turning2 = pygame.image.load('dark_spearlik/standing_turning0007.png')
s_turning3 = pygame.image.load('dark_spearlik/standing_turning0008.png')
s_turning4 = pygame.image.load('dark_spearlik/standing_turning0009.png')
s_turning5 = pygame.image.load('dark_spearlik/standing_turning0010.png')

s_jump_back_left1 = pygame.image.load('dark_spearlik/jump_back0001.png')
s_jump_back_left2 = pygame.image.load('dark_spearlik/jump_back0002.png')
s_jump_back_left3 = pygame.image.load('dark_spearlik/jump_back0003.png')
s_jump_back_left4 = pygame.image.load('dark_spearlik/jump_back0004.png')
s_jump_back_left5 = pygame.image.load('dark_spearlik/jump_back0005.png')

s_jump_back_right1 = pygame.image.load('dark_spearlik/jump_back0006.png')
s_jump_back_right2 = pygame.image.load('dark_spearlik/jump_back0007.png')
s_jump_back_right3 = pygame.image.load('dark_spearlik/jump_back0008.png')
s_jump_back_right4 = pygame.image.load('dark_spearlik/jump_back0009.png')
s_jump_back_right5 = pygame.image.load('dark_spearlik/jump_back0010.png')

s_taunt_left1 = pygame.image.load('dark_spearlik/taunt_left0000.png')
s_taunt_left2 = pygame.image.load('dark_spearlik/taunt_left0001.png')
s_taunt_left3 = pygame.image.load('dark_spearlik/taunt_left0002.png')
s_taunt_left4 = pygame.image.load('dark_spearlik/taunt_left0003.png')
s_taunt_left5 = pygame.image.load('dark_spearlik/taunt_left0004.png')
s_taunt_left6 = pygame.image.load('dark_spearlik/taunt_left0005.png')
s_taunt_left7 = pygame.image.load('dark_spearlik/taunt_left0006.png')
s_taunt_left8 = pygame.image.load('dark_spearlik/taunt_left0007.png')
s_taunt_left9 = pygame.image.load('dark_spearlik/taunt_left0008.png')

s_taunt_right1 = pygame.image.load('dark_spearlik/taunt_right0000.png')
s_taunt_right2 = pygame.image.load('dark_spearlik/taunt_right0001.png')
s_taunt_right3 = pygame.image.load('dark_spearlik/taunt_right0002.png')
s_taunt_right4 = pygame.image.load('dark_spearlik/taunt_right0003.png')
s_taunt_right5 = pygame.image.load('dark_spearlik/taunt_right0004.png')
s_taunt_right6 = pygame.image.load('dark_spearlik/taunt_right0005.png')
s_taunt_right7 = pygame.image.load('dark_spearlik/taunt_right0006.png')
s_taunt_right8 = pygame.image.load('dark_spearlik/taunt_right0007.png')
s_taunt_right9 = pygame.image.load('dark_spearlik/taunt_right0008.png')
s_taunt_right10 = pygame.image.load('dark_spearlik/taunt_right0009.png')

s_strike_left1_1 = pygame.image.load('dark_spearlik/strike_left0000.png')
s_strike_left1_2 = pygame.image.load('dark_spearlik/strike_left0001.png')
s_strike_left1_3 = pygame.image.load('dark_spearlik/strike_left0002.png')
s_strike_left1_4 = pygame.image.load('dark_spearlik/strike_left0003.png')
s_strike_left1_5 = pygame.image.load('dark_spearlik/strike_left0004.png')
s_strike_left1_6 = pygame.image.load('dark_spearlik/strike_left0005.png')

s_strike_left2_1 = pygame.image.load('dark_spearlik/strike_left0006.png')
s_strike_left2_2 = pygame.image.load('dark_spearlik/strike_left0007.png')
s_strike_left2_3 = pygame.image.load('dark_spearlik/strike_left0008.png')
s_strike_left2_4 = pygame.image.load('dark_spearlik/strike_left0009.png')
s_strike_left2_5 = pygame.image.load('dark_spearlik/strike_left0010.png')

s_strike_right1_1 = pygame.image.load('dark_spearlik/strike_right0000.png')
s_strike_right1_2 = pygame.image.load('dark_spearlik/strike_right0001.png')
s_strike_right1_3 = pygame.image.load('dark_spearlik/strike_right0002.png')
s_strike_right1_4 = pygame.image.load('dark_spearlik/strike_right0003.png')
s_strike_right1_5 = pygame.image.load('dark_spearlik/strike_right0004.png')

s_strike_right2_1 = pygame.image.load('dark_spearlik/strike_right0006.png')
s_strike_right2_2 = pygame.image.load('dark_spearlik/strike_right0007.png')
s_strike_right2_3 = pygame.image.load('dark_spearlik/strike_right0008.png')
s_strike_right2_4 = pygame.image.load('dark_spearlik/strike_right0009.png')
s_strike_right2_5 = pygame.image.load('dark_spearlik/strike_right0010.png')

s_walk_left1 = pygame.image.load('dark_spearlik/walking_left0000.png')
s_walk_left2 = pygame.image.load('dark_spearlik/walking_left0001.png')
s_walk_left3 = pygame.image.load('dark_spearlik/walking_left0002.png')
s_walk_left4 = pygame.image.load('dark_spearlik/walking_left0003.png')
s_walk_left5 = pygame.image.load('dark_spearlik/walking_left0004.png')
s_walk_left6 = pygame.image.load('dark_spearlik/walking_left0005.png')
s_walk_left7 = pygame.image.load('dark_spearlik/walking_left0006.png')
s_walk_left8 = pygame.image.load('dark_spearlik/walking_left0007.png')

s_walk_right1 = pygame.image.load('dark_spearlik/walking_right0000.png')
s_walk_right2 = pygame.image.load('dark_spearlik/walking_right0001.png')
s_walk_right3 = pygame.image.load('dark_spearlik/walking_right0002.png')
s_walk_right4 = pygame.image.load('dark_spearlik/walking_right0003.png')
s_walk_right5 = pygame.image.load('dark_spearlik/walking_right0004.png')
s_walk_right6 = pygame.image.load('dark_spearlik/walking_right0005.png')
s_walk_right7 = pygame.image.load('dark_spearlik/walking_right0006.png')
s_walk_right8 = pygame.image.load('dark_spearlik/walking_right0007.png')

s_death_l1_1 = pygame.image.load('dark_spearlik/death_right10000.png')
s_death_l1_2 = pygame.image.load('dark_spearlik/death_right10001.png')
s_death_l1_3 = pygame.image.load('dark_spearlik/death_right10002.png')
s_death_l1_4 = pygame.image.load('dark_spearlik/death_right10003.png')
s_death_l1_5 = pygame.image.load('dark_spearlik/death_right10004.png')
s_death_l1_6 = pygame.image.load('dark_spearlik/death_right10005.png')
s_death_l1_7 = pygame.image.load('dark_spearlik/death_right10006.png')
s_death_l1_8 = pygame.image.load('dark_spearlik/death_right10007.png')
s_death_l1_9 = pygame.image.load('dark_spearlik/death_right10008.png')
s_death_l1_10 = pygame.image.load('dark_spearlik/death_right10009.png')
s_death_l1_11 = pygame.image.load('dark_spearlik/death_right10010.png')
s_death_l1_12 = pygame.image.load('dark_spearlik/death_right10011.png')

s_death_l2_1 = pygame.image.load('dark_spearlik/death_right20000.png')
s_death_l2_2 = pygame.image.load('dark_spearlik/death_right20001.png')
s_death_l2_3 = pygame.image.load('dark_spearlik/death_right20002.png')
s_death_l2_4 = pygame.image.load('dark_spearlik/death_right20003.png')
s_death_l2_5 = pygame.image.load('dark_spearlik/death_right20004.png')
s_death_l2_6 = pygame.image.load('dark_spearlik/death_right20005.png')
s_death_l2_7 = pygame.image.load('dark_spearlik/death_right20006.png')

s_death_l3_1 = pygame.image.load('dark_spearlik/death_right30000.png')
s_death_l3_2 = pygame.image.load('dark_spearlik/death_right30001.png')
s_death_l3_3 = pygame.image.load('dark_spearlik/death_right30002.png')
s_death_l3_4 = pygame.image.load('dark_spearlik/death_right30003.png')
s_death_l3_5 = pygame.image.load('dark_spearlik/death_right30004.png')
s_death_l3_6 = pygame.image.load('dark_spearlik/death_right30005.png')
s_death_l3_7 = pygame.image.load('dark_spearlik/death_right30006.png')

s_death_l4_1 = pygame.image.load('dark_spearlik/death_right40000.png')
s_death_l4_2 = pygame.image.load('dark_spearlik/death_right40001.png')
s_death_l4_3 = pygame.image.load('dark_spearlik/death_right40002.png')
s_death_l4_4 = pygame.image.load('dark_spearlik/death_right40003.png')
s_death_l4_5 = pygame.image.load('dark_spearlik/death_right40004.png')
s_death_l4_6 = pygame.image.load('dark_spearlik/death_right40005.png')
s_death_l4_7 = pygame.image.load('dark_spearlik/death_right40006.png')
s_death_l4_8 = pygame.image.load('dark_spearlik/death_right40007.png')
s_death_l4_9 = pygame.image.load('dark_spearlik/death_right40008.png')

s_death_r1_1 = pygame.image.load('dark_spearlik/death_left10000.png')
s_death_r1_2 = pygame.image.load('dark_spearlik/death_left10001.png')
s_death_r1_3 = pygame.image.load('dark_spearlik/death_left10002.png')
s_death_r1_4 = pygame.image.load('dark_spearlik/death_left10003.png')
s_death_r1_5 = pygame.image.load('dark_spearlik/death_left10004.png')
s_death_r1_6 = pygame.image.load('dark_spearlik/death_left10005.png')
s_death_r1_7 = pygame.image.load('dark_spearlik/death_left10006.png')
s_death_r1_8 = pygame.image.load('dark_spearlik/death_left10007.png')
s_death_r1_9 = pygame.image.load('dark_spearlik/death_left10008.png')

s_death_r2_1 = pygame.image.load('dark_spearlik/death_left20000.png')
s_death_r2_2 = pygame.image.load('dark_spearlik/death_left20001.png')
s_death_r2_3 = pygame.image.load('dark_spearlik/death_left20002.png')
s_death_r2_4 = pygame.image.load('dark_spearlik/death_left20003.png')
s_death_r2_5 = pygame.image.load('dark_spearlik/death_left20004.png')


'''
G O B L I K
'''
g_stand_l1 = pygame.image.load('dark_goblik/standing_turn0000.png')
g_stand_l2 = pygame.image.load('dark_goblik/standing_turn0001.png')
g_stand_l3 = pygame.image.load('dark_goblik/standing_turn0002.png')
g_stand_l4 = pygame.image.load('dark_goblik/standing_turn0003.png')
g_stand_l5 = pygame.image.load('dark_goblik/standing_turn0004.png')

g_stand_r1 = pygame.image.load('dark_goblik/standing_turn0008.png')
g_stand_r2 = pygame.image.load('dark_goblik/standing_turn0009.png')
g_stand_r3 = pygame.image.load('dark_goblik/standing_turn0010.png')
g_stand_r4 = pygame.image.load('dark_goblik/standing_turn0011.png')
g_stand_r5 = pygame.image.load('dark_goblik/standing_turn0012.png')

g_turn1 = pygame.image.load('dark_goblik/standing_turn0005.png')
g_turn2 = pygame.image.load('dark_goblik/standing_turn0006.png')
g_turn3 = pygame.image.load('dark_goblik/standing_turn0007.png')

g_leap_back1 = pygame.image.load('dark_goblik/leap_back0000.png')
g_leap_back2 = pygame.image.load('dark_goblik/leap_back0001.png')
g_leap_back3 = pygame.image.load('dark_goblik/leap_back0002.png')
g_leap_back4 = pygame.image.load('dark_goblik/leap_back0003.png')
g_leap_back5 = pygame.image.load('dark_goblik/leap_back0004.png')

g_taunt_l1 = pygame.image.load('dark_goblik/taunt_left0000.png')
g_taunt_l2 = pygame.image.load('dark_goblik/taunt_left0001.png')
g_taunt_l3 = pygame.image.load('dark_goblik/taunt_left0002.png')
g_taunt_l4 = pygame.image.load('dark_goblik/taunt_left0003.png')
g_taunt_l5 = pygame.image.load('dark_goblik/taunt_left0004.png')
g_taunt_l6 = pygame.image.load('dark_goblik/taunt_left0005.png')
g_taunt_l7 = pygame.image.load('dark_goblik/taunt_left0006.png')
g_taunt_l8 = pygame.image.load('dark_goblik/taunt_left0007.png')
g_taunt_l9 = pygame.image.load('dark_goblik/taunt_left0008.png')
g_taunt_l10 = pygame.image.load('dark_goblik/taunt_left0009.png')
g_taunt_l11 = pygame.image.load('dark_goblik/taunt_left0010.png')
g_taunt_l12 = pygame.image.load('dark_goblik/taunt_left0011.png')
g_taunt_l13 = pygame.image.load('dark_goblik/taunt_left0012.png')
g_taunt_l14 = pygame.image.load('dark_goblik/taunt_left0013.png')

g_taunt_r1 = pygame.image.load('dark_goblik/taunt_right0000.png')
g_taunt_r2 = pygame.image.load('dark_goblik/taunt_right0001.png')
g_taunt_r3 = pygame.image.load('dark_goblik/taunt_right0002.png')
g_taunt_r4 = pygame.image.load('dark_goblik/taunt_right0003.png')
g_taunt_r5 = pygame.image.load('dark_goblik/taunt_right0004.png')
g_taunt_r6 = pygame.image.load('dark_goblik/taunt_right0005.png')
g_taunt_r7 = pygame.image.load('dark_goblik/taunt_right0006.png')
g_taunt_r8 = pygame.image.load('dark_goblik/taunt_right0007.png')
g_taunt_r9 = pygame.image.load('dark_goblik/taunt_right0008.png')
g_taunt_r10 = pygame.image.load('dark_goblik/taunt_right0009.png')
g_taunt_r11 = pygame.image.load('dark_goblik/taunt_right0010.png')
g_taunt_r12 = pygame.image.load('dark_goblik/taunt_right0011.png')
g_taunt_r13 = pygame.image.load('dark_goblik/taunt_right0012.png')
g_taunt_r14 = pygame.image.load('dark_goblik/taunt_right0013.png')

g_walking1_l = pygame.image.load('dark_goblik/walking_turning0000.png')
g_walking2_l = pygame.image.load('dark_goblik/walking_turning0001.png')
g_walking3_l = pygame.image.load('dark_goblik/walking_turning0002.png')
g_walking4_l = pygame.image.load('dark_goblik/walking_turning0003.png')
g_walking5_l = pygame.image.load('dark_goblik/walking_turning0004.png')
g_walking6_l = pygame.image.load('dark_goblik/walking_turning0005.png')
g_walking7_l = pygame.image.load('dark_goblik/walking_turning0006.png')
g_walking8_l = pygame.image.load('dark_goblik/walking_turning0007.png')
g_walking9_l = pygame.image.load('dark_goblik/walking_turning0008.png')
g_walking10_l = pygame.image.load('dark_goblik/walking_turning0009.png')
g_walking11_l = pygame.image.load('dark_goblik/walking_turning0010.png')

g_walking1_r = pygame.image.load('dark_goblik/walking_turning0016.png')
g_walking2_r = pygame.image.load('dark_goblik/walking_turning0017.png')
g_walking3_r = pygame.image.load('dark_goblik/walking_turning0018.png')
g_walking4_r = pygame.image.load('dark_goblik/walking_turning0019.png')
g_walking5_r = pygame.image.load('dark_goblik/walking_turning0020.png')
g_walking6_r = pygame.image.load('dark_goblik/walking_turning0021.png')
g_walking7_r = pygame.image.load('dark_goblik/walking_turning0022.png')
g_walking8_r = pygame.image.load('dark_goblik/walking_turning0023.png')
g_walking9_r = pygame.image.load('dark_goblik/walking_turning0024.png')
g_walking10_r = pygame.image.load('dark_goblik/walking_turning0025.png')
g_walking11_r = pygame.image.load('dark_goblik/walking_turning0026.png')

g_block1_l = pygame.image.load('dark_goblik/block_l0000.png')
g_block2_l = pygame.image.load('dark_goblik/block_l0001.png')
g_block3_l = pygame.image.load('dark_goblik/block_l0002.png')
g_block4_l = pygame.image.load('dark_goblik/block_l0003.png')
g_block5_l = pygame.image.load('dark_goblik/block_l0004.png')
g_block6_l = pygame.image.load('dark_goblik/block_l0005.png')

g_block1_r = pygame.image.load('dark_goblik/block_r0000.png')
g_block2_r = pygame.image.load('dark_goblik/block_r0001.png')
g_block3_r = pygame.image.load('dark_goblik/block_r0002.png')
g_block4_r = pygame.image.load('dark_goblik/block_r0003.png')
g_block5_r = pygame.image.load('dark_goblik/block_r0004.png')

g_strike1_l1 = pygame.image.load('dark_goblik/strike1_l0000.png')
g_strike1_l2 = pygame.image.load('dark_goblik/strike1_l0001.png')
g_strike1_l3 = pygame.image.load('dark_goblik/strike1_l0002.png')
g_strike1_l4 = pygame.image.load('dark_goblik/strike1_l0003.png')
g_strike1_l5 = pygame.image.load('dark_goblik/strike1_l0004.png')
g_strike1_l6 = pygame.image.load('dark_goblik/strike1_l0005.png')

g_strike2_l1 = pygame.image.load('dark_goblik/strike2_l0000.png')
g_strike2_l2 = pygame.image.load('dark_goblik/strike2_l0001.png')
g_strike2_l3 = pygame.image.load('dark_goblik/strike2_l0002.png')
g_strike2_l4 = pygame.image.load('dark_goblik/strike2_l0003.png')
g_strike2_l5 = pygame.image.load('dark_goblik/strike2_l0004.png')
g_strike2_l6 = pygame.image.load('dark_goblik/strike2_l0005.png')
g_strike2_l7 = pygame.image.load('dark_goblik/strike2_l0006.png')
g_strike2_l8 = pygame.image.load('dark_goblik/strike2_l0007.png')
g_strike2_l9 = pygame.image.load('dark_goblik/strike2_l0008.png')
g_strike2_l10 = pygame.image.load('dark_goblik/strike2_l0009.png')

g_jump_strike_l1 = pygame.image.load('dark_goblik/jump_strike_l0000.png')
g_jump_strike_l2 = pygame.image.load('dark_goblik/jump_strike_l0001.png')
g_jump_strike_l3 = pygame.image.load('dark_goblik/jump_strike_l0002.png')
g_jump_strike_l4 = pygame.image.load('dark_goblik/jump_strike_l0003.png')
g_jump_strike_l5 = pygame.image.load('dark_goblik/jump_strike_l0004.png')
g_jump_strike_l6 = pygame.image.load('dark_goblik/jump_strike_l0005.png')

g_strike1_r1 = pygame.image.load('dark_goblik/strike1_r0000.png')
g_strike1_r2 = pygame.image.load('dark_goblik/strike1_r0001.png')
g_strike1_r3 = pygame.image.load('dark_goblik/strike1_r0002.png')
g_strike1_r4 = pygame.image.load('dark_goblik/strike1_r0003.png')
g_strike1_r5 = pygame.image.load('dark_goblik/strike1_r0004.png')
g_strike1_r6 = pygame.image.load('dark_goblik/strike1_r0005.png')
g_strike1_r7 = pygame.image.load('dark_goblik/strike1_r0006.png')

g_jump_strike_r1 = pygame.image.load('dark_goblik/jump_strike_r0000.png')
g_jump_strike_r2 = pygame.image.load('dark_goblik/jump_strike_r0001.png')
g_jump_strike_r3 = pygame.image.load('dark_goblik/jump_strike_r0002.png')
g_jump_strike_r4 = pygame.image.load('dark_goblik/jump_strike_r0003.png')
g_jump_strike_r5 = pygame.image.load('dark_goblik/jump_strike_r0004.png')
g_jump_strike_r6 = pygame.image.load('dark_goblik/jump_strike_r0005.png')

g_dead1_l1 = pygame.image.load('dark_goblik/dead1_l0000.png')
g_dead1_l2 = pygame.image.load('dark_goblik/dead1_l0001.png')
g_dead1_l3 = pygame.image.load('dark_goblik/dead1_l0002.png')
g_dead1_l4 = pygame.image.load('dark_goblik/dead1_l0003.png')
g_dead1_l5 = pygame.image.load('dark_goblik/dead1_l0004.png')
g_dead1_l6 = pygame.image.load('dark_goblik/dead1_l0005.png')
g_dead1_l7 = pygame.image.load('dark_goblik/dead1_l0006.png')
g_dead1_l8 = pygame.image.load('dark_goblik/dead1_l0007.png')

g_dead2_l1 = pygame.image.load('dark_goblik/dead2_l0000.png')
g_dead2_l2 = pygame.image.load('dark_goblik/dead2_l0001.png')
g_dead2_l3 = pygame.image.load('dark_goblik/dead2_l0002.png')
g_dead2_l4 = pygame.image.load('dark_goblik/dead2_l0003.png')
g_dead2_l5 = pygame.image.load('dark_goblik/dead2_l0004.png')
g_dead2_l6 = pygame.image.load('dark_goblik/dead2_l0005.png')
g_dead2_l7 = pygame.image.load('dark_goblik/dead2_l0006.png')
g_dead2_l8 = pygame.image.load('dark_goblik/dead2_l0007.png')

g_dead3_l1 = pygame.image.load('dark_goblik/dead3_l0000.png')
g_dead3_l2 = pygame.image.load('dark_goblik/dead3_l0001.png')
g_dead3_l3 = pygame.image.load('dark_goblik/dead3_l0002.png')
g_dead3_l4 = pygame.image.load('dark_goblik/dead3_l0003.png')
g_dead3_l5 = pygame.image.load('dark_goblik/dead3_l0004.png')
g_dead3_l6 = pygame.image.load('dark_goblik/dead3_l0005.png')
g_dead3_l7 = pygame.image.load('dark_goblik/dead3_l0006.png')

g_dead4_l1 = pygame.image.load('dark_goblik/dead4_l0000.png')
g_dead4_l2 = pygame.image.load('dark_goblik/dead4_l0001.png')
g_dead4_l3 = pygame.image.load('dark_goblik/dead4_l0002.png')
g_dead4_l4 = pygame.image.load('dark_goblik/dead4_l0003.png')
g_dead4_l5 = pygame.image.load('dark_goblik/dead4_l0004.png')
g_dead4_l6 = pygame.image.load('dark_goblik/dead4_l0005.png')
g_dead4_l7 = pygame.image.load('dark_goblik/dead4_l0006.png')
g_dead4_l8 = pygame.image.load('dark_goblik/dead4_l0007.png')
g_dead4_l9 = pygame.image.load('dark_goblik/dead4_l0008.png')
g_dead4_l10 = pygame.image.load('dark_goblik/dead4_l0009.png')
g_dead4_l11 = pygame.image.load('dark_goblik/dead4_l0010.png')
g_dead4_l12 = pygame.image.load('dark_goblik/dead4_l0011.png')
g_dead4_l13 = pygame.image.load('dark_goblik/dead4_l0012.png')
g_dead4_l14 = pygame.image.load('dark_goblik/dead4_l0013.png')

g_dead5_l1 = pygame.image.load('dark_goblik/dead5_l0000.png')
g_dead5_l2 = pygame.image.load('dark_goblik/dead5_l0001.png')
g_dead5_l3 = pygame.image.load('dark_goblik/dead5_l0002.png')
g_dead5_l4 = pygame.image.load('dark_goblik/dead5_l0003.png')
g_dead5_l5 = pygame.image.load('dark_goblik/dead5_l0004.png')
g_dead5_l6 = pygame.image.load('dark_goblik/dead5_l0005.png')
g_dead5_l7 = pygame.image.load('dark_goblik/dead5_l0006.png')
g_dead5_l8 = pygame.image.load('dark_goblik/dead5_l0007.png')

g_dead1_r1 = pygame.image.load('dark_goblik/dead1_r0000.png')
g_dead1_r2 = pygame.image.load('dark_goblik/dead1_r0001.png')
g_dead1_r3 = pygame.image.load('dark_goblik/dead1_r0002.png')
g_dead1_r4 = pygame.image.load('dark_goblik/dead1_r0003.png')
g_dead1_r5 = pygame.image.load('dark_goblik/dead1_r0004.png')
g_dead1_r6 = pygame.image.load('dark_goblik/dead1_r0005.png')
g_dead1_r7 = pygame.image.load('dark_goblik/dead1_r0006.png')
g_dead1_r8 = pygame.image.load('dark_goblik/dead1_r0007.png')

g_dead2_r1 = pygame.image.load('dark_goblik/dead2_r0000.png')
g_dead2_r2 = pygame.image.load('dark_goblik/dead2_r0001.png')
g_dead2_r3 = pygame.image.load('dark_goblik/dead2_r0002.png')
g_dead2_r4 = pygame.image.load('dark_goblik/dead2_r0003.png')
g_dead2_r5 = pygame.image.load('dark_goblik/dead2_r0004.png')
g_dead2_r6 = pygame.image.load('dark_goblik/dead2_r0005.png')
g_dead2_r7 = pygame.image.load('dark_goblik/dead2_r0006.png')
g_dead2_r8 = pygame.image.load('dark_goblik/dead2_r0007.png')
g_dead2_r9 = pygame.image.load('dark_goblik/dead2_r0008.png')

g_dead3_r1 = pygame.image.load('dark_goblik/dead3_r0000.png')
g_dead3_r2 = pygame.image.load('dark_goblik/dead3_r0001.png')
g_dead3_r3 = pygame.image.load('dark_goblik/dead3_r0002.png')
g_dead3_r4 = pygame.image.load('dark_goblik/dead3_r0003.png')
g_dead3_r5 = pygame.image.load('dark_goblik/dead3_r0004.png')
g_dead3_r6 = pygame.image.load('dark_goblik/dead3_r0005.png')



# H E R O

stand1 = pygame.image.load('dark_figure/standing_turning0078.png')
stand2 = pygame.image.load('dark_figure/standing_turning0079.png')
stand3 = pygame.image.load('dark_figure/standing_turning0080.png')
stand4 = pygame.image.load('dark_figure/standing_turning0081.png')
turn1 = pygame.image.load('dark_figure/standing_turning0082.png')
turn2 = pygame.image.load('dark_figure/standing_turning0083.png')
turn3 = pygame.image.load('dark_figure/standing_turning0084.png')
stand5 = pygame.image.load('dark_figure/standing_turning0085.png')
stand6 = pygame.image.load('dark_figure/standing_turning0086.png')
stand7 = pygame.image.load('dark_figure/standing_turning0087.png')
stand8 = pygame.image.load('dark_figure/standing_turning0088.png')
turn4 = pygame.image.load('dark_figure/standing_turning0089.png')
turn5 = pygame.image.load('dark_figure/standing_turning0090.png')
turn6 = pygame.image.load('dark_figure/standing_turning0091.png')

turn_running_l1 = pygame.image.load('dark_figure/turning_running_l0001.png')
turn_running_l2 = pygame.image.load('dark_figure/turning_running_l0002.png')
turn_running_l3 = pygame.image.load('dark_figure/turning_running_l0003.png')
turn_running_l4 = pygame.image.load('dark_figure/turning_running_l0004.png')

turn_running_r1 = pygame.image.load('dark_figure/turning_running_r0085.png')
turn_running_r2 = pygame.image.load('dark_figure/turning_running_r0086.png')
turn_running_r3 = pygame.image.load('dark_figure/turning_running_r0087.png')
turn_running_r4 = pygame.image.load('dark_figure/turning_running_r0088.png')

running_l1 = pygame.image.load('dark_figure/running_l0015.png')
running_l2 = pygame.image.load('dark_figure/running_l0016.png')
running_l3 = pygame.image.load('dark_figure/running_l0017.png')
running_l4 = pygame.image.load('dark_figure/running_l0018.png')
running_l5 = pygame.image.load('dark_figure/running_l0019.png')
running_l6 = pygame.image.load('dark_figure/running_l0020.png')
running_l7 = pygame.image.load('dark_figure/running_l0021.png')
running_l8 = pygame.image.load('dark_figure/running_l0022.png')

running_r1 = pygame.image.load('dark_figure/running_r0089.png')
running_r2 = pygame.image.load('dark_figure/running_r0090.png')
running_r3 = pygame.image.load('dark_figure/running_r0091.png')
running_r4 = pygame.image.load('dark_figure/running_r0092.png')
running_r5 = pygame.image.load('dark_figure/running_r0093.png')
running_r6 = pygame.image.load('dark_figure/running_r0094.png')
running_r7 = pygame.image.load('dark_figure/running_r0095.png')
running_r8 = pygame.image.load('dark_figure/running_r0096.png')

sword_walk_r1 = pygame.image.load('dark_figure/sword_walking0000.png')
sword_walk_r2 = pygame.image.load('dark_figure/sword_walking0001.png')
sword_walk_r3 = pygame.image.load('dark_figure/sword_walking0002.png')
sword_walk_r4 = pygame.image.load('dark_figure/sword_walking0003.png')
sword_walk_r5 = pygame.image.load('dark_figure/sword_walking0004.png')
sword_walk_r6 = pygame.image.load('dark_figure/sword_walking0005.png')
sword_walk_r7 = pygame.image.load('dark_figure/sword_walking0006.png')
sword_walk_r8 = pygame.image.load('dark_figure/sword_walking0007.png')
sword_walk_r9 = pygame.image.load('dark_figure/sword_walking0008.png')
sword_walk_r10 = pygame.image.load('dark_figure/sword_walking0009.png')

sword_walk_l1 = pygame.image.load('dark_figure/sword_walking0011.png')
sword_walk_l2 = pygame.image.load('dark_figure/sword_walking0012.png')
sword_walk_l3 = pygame.image.load('dark_figure/sword_walking0013.png')
sword_walk_l4 = pygame.image.load('dark_figure/sword_walking0014.png')
sword_walk_l5 = pygame.image.load('dark_figure/sword_walking0015.png')
sword_walk_l6 = pygame.image.load('dark_figure/sword_walking0016.png')
sword_walk_l7 = pygame.image.load('dark_figure/sword_walking0017.png')
sword_walk_l8 = pygame.image.load('dark_figure/sword_walking0018.png')
sword_walk_l9 = pygame.image.load('dark_figure/sword_walking0019.png')
sword_walk_l10 = pygame.image.load('dark_figure/sword_walking0020.png')

sword_edge_r = pygame.image.load('dark_figure/sword_edge0001.png')
sword_edge_l = pygame.image.load('dark_figure/sword_edge0000.png')

sword_in_air_r = pygame.image.load('dark_figure/sword_fall_jump0001.png')
sword_in_air_l = pygame.image.load('dark_figure/sword_fall_jump0003.png')

sword_jump_r = pygame.image.load('dark_figure/sword_fall_jump0000.png')
sword_jump_l = pygame.image.load('dark_figure/sword_fall_jump0002.png')

sword_landing_r1 = pygame.image.load('dark_figure/sword_landing_r0000.png')
sword_landing_r2 = pygame.image.load('dark_figure/sword_landing_r0001.png')

sword_landing_l1 = pygame.image.load('dark_figure/sword_landing_l0000.png')
sword_landing_l2 = pygame.image.load('dark_figure/sword_landing_l0001.png')

in_air_r = pygame.image.load('dark_figure/jumping_right0006.png')
in_air_l = pygame.image.load('dark_figure/jumping_left0006.png')

landing_r1 = pygame.image.load('dark_figure/jumping_right0008.png')
landing_r2 = pygame.image.load('dark_figure/jumping_right0009.png')
landing_r3 = pygame.image.load('dark_figure/jumping_right0010.png')

landing_l1 = pygame.image.load('dark_figure/jumping_left0008.png')
landing_l2 = pygame.image.load('dark_figure/jumping_left0009.png')
landing_l3 = pygame.image.load('dark_figure/jumping_left0010.png')

in_air_standing_r = pygame.image.load('dark_figure/jumping_right0007.png')
in_air_standing_r2 = pygame.image.load('dark_figure/jumping_right0011.png')
in_air_standing_l = pygame.image.load('dark_figure/jumping_left0007.png')
in_air_standing_l2 = pygame.image.load('dark_figure/jumping_left0011.png')

climbing1 = pygame.image.load('dark_figure/climbing0000.png')
climbing2 = pygame.image.load('dark_figure/climbing0001.png')
climbing3 = pygame.image.load('dark_figure/climbing0002.png')
climbing4 = pygame.image.load('dark_figure/climbing0003.png')
climbing5 = pygame.image.load('dark_figure/climbing0004.png')
climbing6 = pygame.image.load('dark_figure/climbing0005.png')
climbing7 = pygame.image.load('dark_figure/climbing0006.png')

on_edge_l = pygame.image.load('dark_figure/jumping_left0010.png')
on_edge_r = pygame.image.load('dark_figure/jumping_right0010.png')

stop_running_l1 = pygame.image.load('dark_figure/running_l_stopping0013.png')
stop_running_l2 = pygame.image.load('dark_figure/running_l_stopping0014.png')

stop_running_r1 = pygame.image.load('dark_figure/running_r_stopping0097.png')
stop_running_r2 = pygame.image.load('dark_figure/running_r_stopping0098.png')

sword_r1 = pygame.image.load('dark_figure/sword_out_standing0001.png')
sword_r2 = pygame.image.load('dark_figure/sword_out_standing0002.png')
sword_r3 = pygame.image.load('dark_figure/sword_out_standing0003.png')
sword_r4 = pygame.image.load('dark_figure/sword_out_standing0004.png')

sword_turn_rl1 = pygame.image.load('dark_figure/sword_out_standing0005.png')
sword_turn_rl2 = pygame.image.load('dark_figure/sword_out_standing0006.png')
sword_turn_rl3 = pygame.image.load('dark_figure/sword_out_standing0007.png')

sword_l1 = pygame.image.load('dark_figure/sword_out_standing0008.png')
sword_l2 = pygame.image.load('dark_figure/sword_out_standing0009.png')
sword_l3 = pygame.image.load('dark_figure/sword_out_standing0010.png')
sword_l4 = pygame.image.load('dark_figure/sword_out_standing0011.png')

sword_turn_lr1 = pygame.image.load('dark_figure/sword_out_standing0012.png')
sword_turn_lr2 = pygame.image.load('dark_figure/sword_out_standing0013.png')
sword_turn_lr3 = pygame.image.load('dark_figure/sword_out_standing0014.png')

draw_swordr1 = pygame.image.load('dark_figure/sword_out_r0000.png')
draw_swordr2 = pygame.image.load('dark_figure/sword_out_r0001.png')
draw_swordr3 = pygame.image.load('dark_figure/sword_out_r0002.png')
draw_swordr4 = pygame.image.load('dark_figure/sword_out_r0003.png')
draw_swordr5 = pygame.image.load('dark_figure/sword_out_r0004.png')
draw_swordr6 = pygame.image.load('dark_figure/sword_out_r0005.png')
draw_swordr7 = pygame.image.load('dark_figure/sword_out_r0006.png')
draw_swordr8 = pygame.image.load('dark_figure/sword_out_r0007.png')
draw_swordr9 = pygame.image.load('dark_figure/sword_out_r0008.png')

sword_awayr1 = pygame.image.load('dark_figure/sword_away_r0000.png')
sword_awayr2 = pygame.image.load('dark_figure/sword_away_r0001.png')
sword_awayr3 = pygame.image.load('dark_figure/sword_away_r0002.png')
sword_awayr4 = pygame.image.load('dark_figure/sword_away_r0003.png')
sword_awayr5 = pygame.image.load('dark_figure/sword_away_r0004.png')
sword_awayr6 = pygame.image.load('dark_figure/sword_away_r0005.png')
sword_awayr7 = pygame.image.load('dark_figure/sword_away_r0006.png')
sword_awayr8 = pygame.image.load('dark_figure/sword_away_r0007.png')
sword_awayr9 = pygame.image.load('dark_figure/sword_away_r0008.png')
sword_awayr10 = pygame.image.load('dark_figure/sword_away_r0009.png')

draw_swordl1 = pygame.image.load('dark_figure/sword_out_l0000.png')
draw_swordl2 = pygame.image.load('dark_figure/sword_out_l0001.png')
draw_swordl3 = pygame.image.load('dark_figure/sword_out_l0002.png')
draw_swordl4 = pygame.image.load('dark_figure/sword_out_l0003.png')
draw_swordl5 = pygame.image.load('dark_figure/sword_out_l0004.png')
draw_swordl6 = pygame.image.load('dark_figure/sword_out_l0005.png')
draw_swordl7 = pygame.image.load('dark_figure/sword_out_l0006.png')
draw_swordl8 = pygame.image.load('dark_figure/sword_out_l0007.png')
draw_swordl9 = pygame.image.load('dark_figure/sword_out_l0008.png')

sword_awayl1 = pygame.image.load('dark_figure/sword_away_l0000.png')
sword_awayl2 = pygame.image.load('dark_figure/sword_away_l0001.png')
sword_awayl3 = pygame.image.load('dark_figure/sword_away_l0002.png')
sword_awayl4 = pygame.image.load('dark_figure/sword_away_l0003.png')
sword_awayl5 = pygame.image.load('dark_figure/sword_away_l0004.png')
sword_awayl6 = pygame.image.load('dark_figure/sword_away_l0005.png')
sword_awayl7 = pygame.image.load('dark_figure/sword_away_l0006.png')
sword_awayl8 = pygame.image.load('dark_figure/sword_away_l0007.png')
sword_awayl9 = pygame.image.load('dark_figure/sword_away_l0008.png')
sword_awayl10 = pygame.image.load('dark_figure/sword_away_l0009.png')

leap_forward_r1 = pygame.image.load('dark_figure/sword_leaping0001.png')
leap_forward_r2 = pygame.image.load('dark_figure/sword_leaping0002.png')
leap_forward_r3 = pygame.image.load('dark_figure/sword_leaping0003.png')
leap_forward_r4 = pygame.image.load('dark_figure/sword_leaping0004.png')
leap_forward_r5 = pygame.image.load('dark_figure/sword_leaping0005.png')

leap_back_r1 = pygame.image.load('dark_figure/sword_leaping0007.png')
leap_back_r2 = pygame.image.load('dark_figure/sword_leaping0008.png')
leap_back_r3 = pygame.image.load('dark_figure/sword_leaping0009.png')
leap_back_r4 = pygame.image.load('dark_figure/sword_leaping0010.png')

leap_forward_l1 = pygame.image.load('dark_figure/sword_leaping0012.png')
leap_forward_l2 = pygame.image.load('dark_figure/sword_leaping0013.png')
leap_forward_l3 = pygame.image.load('dark_figure/sword_leaping0014.png')
leap_forward_l4 = pygame.image.load('dark_figure/sword_leaping0015.png')
leap_forward_l5 = pygame.image.load('dark_figure/sword_leaping0016.png')

leap_back_l1 = pygame.image.load('dark_figure/sword_leaping0018.png')
leap_back_l2 = pygame.image.load('dark_figure/sword_leaping0019.png')
leap_back_l3 = pygame.image.load('dark_figure/sword_leaping0020.png')
leap_back_l4 = pygame.image.load('dark_figure/sword_leaping0021.png')

jump_strike1_l1 = pygame.image.load('dark_figure/jump_strike1_l0000.png')
jump_strike1_l2 = pygame.image.load('dark_figure/jump_strike1_l0001.png')
jump_strike1_l3 = pygame.image.load('dark_figure/jump_strike1_l0002.png')
jump_strike1_l4 = pygame.image.load('dark_figure/jump_strike1_l0003.png')
jump_strike1_l5 = pygame.image.load('dark_figure/jump_strike1_l0004.png')
jump_strike1_l6 = pygame.image.load('dark_figure/jump_strike1_l0005.png')
jump_strike1_l7 = pygame.image.load('dark_figure/jump_strike1_l0006.png')

jump_strike2_l1 = pygame.image.load('dark_figure/jump_strike2_l0000.png')
jump_strike2_l2 = pygame.image.load('dark_figure/jump_strike2_l0001.png')
jump_strike2_l3 = pygame.image.load('dark_figure/jump_strike2_l0002.png')
jump_strike2_l4 = pygame.image.load('dark_figure/jump_strike2_l0003.png')
jump_strike2_l5 = pygame.image.load('dark_figure/jump_strike2_l0004.png')
jump_strike2_l6 = pygame.image.load('dark_figure/jump_strike2_l0005.png')

jump_strike1_r1 = pygame.image.load('dark_figure/jump_strike1_r0001.png')
jump_strike1_r2 = pygame.image.load('dark_figure/jump_strike1_r0002.png')
jump_strike1_r3 = pygame.image.load('dark_figure/jump_strike1_r0003.png')
jump_strike1_r4 = pygame.image.load('dark_figure/jump_strike1_r0004.png')
jump_strike1_r5 = pygame.image.load('dark_figure/jump_strike1_r0005.png')
jump_strike1_r6 = pygame.image.load('dark_figure/jump_strike1_r0006.png')
jump_strike1_r7 = pygame.image.load('dark_figure/jump_strike1_r0007.png')

jump_strike2_r1 = pygame.image.load('dark_figure/jump_strike2_r0000.png')
jump_strike2_r2 = pygame.image.load('dark_figure/jump_strike2_r0001.png')
jump_strike2_r3 = pygame.image.load('dark_figure/jump_strike2_r0002.png')
jump_strike2_r4 = pygame.image.load('dark_figure/jump_strike2_r0003.png')
jump_strike2_r5 = pygame.image.load('dark_figure/jump_strike2_r0004.png')
jump_strike2_r6 = pygame.image.load('dark_figure/jump_strike2_r0005.png')

strike1_l1 = pygame.image.load('dark_figure/strike1_l0000.png')
strike1_l2 = pygame.image.load('dark_figure/strike1_l0001.png')
strike1_l3 = pygame.image.load('dark_figure/strike1_l0002.png')
strike1_l4 = pygame.image.load('dark_figure/strike1_l0003.png')
strike1_l5 = pygame.image.load('dark_figure/strike1_l0004.png')
strike1_l6 = pygame.image.load('dark_figure/strike1_l0005.png')
strike1_l7 = pygame.image.load('dark_figure/strike1_l0006.png')

strike2_l1 = pygame.image.load('dark_figure/strike2_l0000.png')
strike2_l2 = pygame.image.load('dark_figure/strike2_l0001.png')
strike2_l3 = pygame.image.load('dark_figure/strike2_l0002.png')
strike2_l4 = pygame.image.load('dark_figure/strike2_l0003.png')
strike2_l5 = pygame.image.load('dark_figure/strike2_l0004.png')
strike2_l6 = pygame.image.load('dark_figure/strike2_l0005.png')
strike2_l7 = pygame.image.load('dark_figure/strike2_l0006.png')
#thrust
strike3_l1 = pygame.image.load('dark_figure/strike3_l0000.png')
strike3_l2 = pygame.image.load('dark_figure/strike3_l0001.png')
strike3_l3 = pygame.image.load('dark_figure/strike3_l0002.png')
strike3_l4 = pygame.image.load('dark_figure/strike3_l0003.png')
strike3_l5 = pygame.image.load('dark_figure/strike3_l0004.png')
#spin
strike4_l1 = pygame.image.load('dark_figure/strike4_l0000.png')
strike4_l2 = pygame.image.load('dark_figure/strike4_l0001.png')
strike4_l3 = pygame.image.load('dark_figure/strike4_l0002.png')
strike4_l4 = pygame.image.load('dark_figure/strike4_l0003.png')
strike4_l5 = pygame.image.load('dark_figure/strike4_l0004.png')
strike4_l6 = pygame.image.load('dark_figure/strike4_l0005.png')
strike4_l7 = pygame.image.load('dark_figure/strike4_l0006.png')

strike1_r1 = pygame.image.load('dark_figure/strike1_r0000.png')
strike1_r2 = pygame.image.load('dark_figure/strike1_r0001.png')
strike1_r3 = pygame.image.load('dark_figure/strike1_r0002.png')
strike1_r4 = pygame.image.load('dark_figure/strike1_r0003.png')
strike1_r5 = pygame.image.load('dark_figure/strike1_r0004.png')
strike1_r6 = pygame.image.load('dark_figure/strike1_r0005.png')
strike1_r7 = pygame.image.load('dark_figure/strike1_r0006.png')

strike2_r1 = pygame.image.load('dark_figure/strike2_r0000.png')
strike2_r2 = pygame.image.load('dark_figure/strike2_r0001.png')
strike2_r3 = pygame.image.load('dark_figure/strike2_r0002.png')
strike2_r4 = pygame.image.load('dark_figure/strike2_r0003.png')
strike2_r5 = pygame.image.load('dark_figure/strike2_r0004.png')
strike2_r6 = pygame.image.load('dark_figure/strike2_r0005.png')
strike2_r7 = pygame.image.load('dark_figure/strike2_r0006.png')
#thrust
strike3_r1 = pygame.image.load('dark_figure/strike3_r0000.png')
strike3_r2 = pygame.image.load('dark_figure/strike3_r0001.png')
strike3_r3 = pygame.image.load('dark_figure/strike3_r0002.png')
strike3_r4 = pygame.image.load('dark_figure/strike3_r0003.png')
strike3_r5 = pygame.image.load('dark_figure/strike3_r0004.png')
#spin
strike4_r1 = pygame.image.load('dark_figure/strike4_r0000.png')
strike4_r2 = pygame.image.load('dark_figure/strike4_r0001.png')
strike4_r3 = pygame.image.load('dark_figure/strike4_r0002.png')
strike4_r4 = pygame.image.load('dark_figure/strike4_r0003.png')
strike4_r5 = pygame.image.load('dark_figure/strike4_r0004.png')
strike4_r6 = pygame.image.load('dark_figure/strike4_r0005.png')
strike4_r7 = pygame.image.load('dark_figure/strike4_r0006.png')

air_strike_r1 = pygame.image.load('dark_figure/air_strike_right0001.png')
air_strike_r2 = pygame.image.load('dark_figure/air_strike_right0002.png')
air_strike_r3 = pygame.image.load('dark_figure/air_strike_right0003.png')
air_strike_r4 = pygame.image.load('dark_figure/air_strike_right0004.png')
air_strike_r5 = pygame.image.load('dark_figure/air_strike_right0005.png')

air_strike_l1 = pygame.image.load('dark_figure/air_strike_left0001.png')
air_strike_l2 = pygame.image.load('dark_figure/air_strike_left0002.png')
air_strike_l3 = pygame.image.load('dark_figure/air_strike_left0003.png')
air_strike_l4 = pygame.image.load('dark_figure/air_strike_left0004.png')
air_strike_l5 = pygame.image.load('dark_figure/air_strike_left0005.png')

blocked_l1 = pygame.image.load('dark_figure/blocked_l001.png')
blocked_l2 = pygame.image.load('dark_figure/blocked_l002.png')
blocked_l3 = pygame.image.load('dark_figure/blocked_l003.png')
blocked_l4 = pygame.image.load('dark_figure/blocked_l004.png')
blocked_l5 = pygame.image.load('dark_figure/blocked_l005.png')

blocked_r1 = pygame.image.load('dark_figure/blocked_r001.png')
blocked_r2 = pygame.image.load('dark_figure/blocked_r002.png')
blocked_r3 = pygame.image.load('dark_figure/blocked_r003.png')
blocked_r4 = pygame.image.load('dark_figure/blocked_r004.png')
blocked_r5 = pygame.image.load('dark_figure/blocked_r005.png') 

block_r1 = pygame.image.load('dark_figure/block_right0000.png')
block_r2 = pygame.image.load('dark_figure/block_right0001.png')
block_r3 = pygame.image.load('dark_figure/block_right0002.png')

block_l1 = pygame.image.load('dark_figure/block_left0000.png')
block_l2 = pygame.image.load('dark_figure/block_left0001.png')
block_l3 = pygame.image.load('dark_figure/block_left0002.png')

blocking1_r1 = pygame.image.load('dark_figure/blocking_right0000.png')
blocking1_r2 = pygame.image.load('dark_figure/blocking_right0001.png')

blocking2_r1 = pygame.image.load('dark_figure/blocking_right20000.png')
blocking2_r2 = pygame.image.load('dark_figure/blocking_right20001.png')

blocking1_l1 = pygame.image.load('dark_figure/blocking_left0000.png')
blocking1_l2 = pygame.image.load('dark_figure/blocking_left0001.png')

blocking2_l1 = pygame.image.load('dark_figure/blocking_left20000.png')
blocking2_l2 = pygame.image.load('dark_figure/blocking_left20001.png')

hurt_r = pygame.image.load('dark_figure/hurt0000.png')
hurt_l = pygame.image.load('dark_figure/hurt0001.png')

nosword_hurt_r = pygame.image.load('dark_figure/hurt_no_sword0000.png')
nosword_hurt_l = pygame.image.load('dark_figure/hurt_no_sword0001.png')

# GRAPHIC

block_graph1_1 = pygame.image.load('dark_graphic/block_graphic0000.png')
block_graph1_2 = pygame.image.load('dark_graphic/block_graphic0001.png')
block_graph1_3 = pygame.image.load('dark_graphic/block_graphic0002.png')
block_graph1_4 = pygame.image.load('dark_graphic/block_graphic0003.png')

block_graph2_1 = pygame.image.load('dark_graphic/block_graphic0005.png')
block_graph2_2 = pygame.image.load('dark_graphic/block_graphic0006.png')
block_graph2_3 = pygame.image.load('dark_graphic/block_graphic0007.png')
block_graph2_4 = pygame.image.load('dark_graphic/block_graphic0008.png')

block_graph3_1 = pygame.image.load('dark_graphic/block_graphic0010.png')
block_graph3_2 = pygame.image.load('dark_graphic/block_graphic0011.png')
block_graph3_3 = pygame.image.load('dark_graphic/block_graphic0012.png')
block_graph3_4 = pygame.image.load('dark_graphic/block_graphic0013.png')

blood_graph1_1 = pygame.image.load('dark_graphic/blood_graphic0000.png')
blood_graph1_2 = pygame.image.load('dark_graphic/blood_graphic0001.png')
blood_graph1_3 = pygame.image.load('dark_graphic/blood_graphic0002.png')
blood_graph1_4 = pygame.image.load('dark_graphic/blood_graphic0003.png')

blood_graph2_1 = pygame.image.load('dark_graphic/blood_graphic0004.png')
blood_graph2_2 = pygame.image.load('dark_graphic/blood_graphic0005.png')
blood_graph2_3 = pygame.image.load('dark_graphic/blood_graphic0006.png')
blood_graph2_4 = pygame.image.load('dark_graphic/blood_graphic0007.png')

blood_graph3_1 = pygame.image.load('dark_graphic/blood_graphic0010.png')
blood_graph3_2 = pygame.image.load('dark_graphic/blood_graphic0011.png')
blood_graph3_3 = pygame.image.load('dark_graphic/blood_graphic0012.png')
blood_graph3_4 = pygame.image.load('dark_graphic/blood_graphic0013.png')

b_open1 = pygame.image.load('dark_graphic/bubble_open0000.png')
b_open2 = pygame.image.load('dark_graphic/bubble_open0001.png')
b_open3 = pygame.image.load('dark_graphic/bubble_open0002.png')
b_open4 = pygame.image.load('dark_graphic/bubble_open0003.png')
b_open5 = pygame.image.load('dark_graphic/bubble_open0004.png')
b_open6 = pygame.image.load('dark_graphic/bubble_open0005.png')

b_close1 = pygame.image.load('dark_graphic/bubble_close0001.png')
b_close2 = pygame.image.load('dark_graphic/bubble_close0002.png')
b_close3 = pygame.image.load('dark_graphic/bubble_close0003.png')
b_close4 = pygame.image.load('dark_graphic/bubble_close0004.png')
b_close5 = pygame.image.load('dark_graphic/bubble_close0005.png')


